### ISSUE TITLE
You predict the noise from the noise-free VAE latents for timestep 300?

### ISSUE THREAD

**Issue by chrisoffner** [PotatoTian/DiffSeg#1]
This is more of a question than necessarily an _issue_ but I'm a student trying to understand your code.

It seems to me that you're directly passing the VAE latents to the Stable Diffusion model, _without adding any noise,_ then predict the noise for `timestep = 300`. Whenever `timestep` is not `None`, there appears to be no noise added to the latents, and so the `self.diffusion_model.predict_on_batch` calls in 

https://github.com/PotatoTian/DiffSeg/blob/8acc7084fd2200b64bb2839471e36928ccb20b9b/diffusion_models/stable_diffusion.py#L194-L196

(if a conditional `context` is used) and 

https://github.com/PotatoTian/DiffSeg/blob/8acc7084fd2200b64bb2839471e36928ccb20b9b/diffusion_models/stable_diffusion.py#L198-L200

(if no explicit `context` is used) would just use the original VAE latents.

Isn't there a mismatch between those latents, which I believe would correspond to `timestep = 1000` (the fully denoised image), and the `timestep = 300` for which you're extracting the (self-)attention maps?

It still seems to work fine, but I wonder if the attention maps obtained this way actually match the attention maps that would naturally "occur" during a standard run through the **[loop](https://github.com/PotatoTian/DiffSeg/blob/8acc7084fd2200b64bb2839471e36928ccb20b9b/diffusion_models/stable_diffusion.py#L219C12-L219C12)** of all `num_steps` time steps, which isn't executed in this single-timestep-extraction method.

**Comment by PotatoTian** [comment]
Hi,

You are right. Theoretically, there should be a mismatch between the latent vectors. Empirically, the `timestep` 300 is sufficient because for most stable diffusion models ~50 steps of denoising are sufficient to produce visually noise-free images. This means that for sufficiently large enough timestep, the latent vectors are approximately almost noise-free.  

However, this shouldn't stop you from using any other timestep, e.g., 1000.  If you notice a significant difference in quality with a different `timestep` setting, please let me know. Thanks!

Best

**Comment by chrisoffner** [comment]
Thank you for the clarification. 🙂
